AllCops:
  DisplayCopNames: true
  TargetRubyVersion: 2.6
  Exclude:
    - 'spec/**/*'

Metrics/LineLength:
  Max: 120

Style/FrozenStringLiteralComment:
  Enabled: false

Documentation:
  Enabled: false
